spring.application.name=reservator
spring.output.ansi.enabled=always
spring.docker.compose.enabled=true
springdoc.api-docs.enabled=false
spring.jpa.open-in-view=false
spring.h2.console.enabled=false
logging.level.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

api.title=Reservator API
api.version=0.1.1
api.description=Multi-tenant reservation engine for generic resources (courts, rooms, etc.) with configurable time slots, schedule management, and a full reservation lifecycle (hold -> book -> confirm).