gatling {
  core {
    outputDirectoryBaseName = "reservator"
    runDescription = "Reservator Load Test"
    encoding = "utf-8"
  }
  http {
    enableGA = false
  }
  data {
    writers = [console, file]
  }
}
